@startuml

participant "User" as User order 5
participant "Veraison\Corim\ncocli" as CoRIM order 10
participant "Veraison\napiclient" as API order 20
participant "Veraison\nProvisioning" as PROV order 30

group construction of corim cbor data for provisioning endorsements

	User --> CoRIM: cocli comid create --template mycomid-templ.json
	CoRIM --> User: created "/tmp/mycomid-templ.cbor" from "mycomid-templ.json"
	User --> CoRIM: cocli corim create --template mycorim-templ.json -m mycomid-templ.cbor -o mycorim.cbor
	CoRIM --> User: created "mycorim.cbor" from "mycorim-templ.json"
end

group end to end provisioning flow
	User -> CoRIM: cocli corim submit corim-file=mycorim.cbor\napi-server=http://veraison.example/endorsement-provisioning/v1/submit\nmedia-type="application/corim-unsigned+cbor; profile=http://arm.com/psa/iot/1"
	CoRIM -> API: setSubmitURI(uri)
    	API -> CoRIM: ok
    	CoRIM -> API: Run(data=mycorim.cbor, mediaType)
    	API -> PROV: POST /endorsement-provisioning/v1/submit Header:{mediaType} Body:{mycorim.cbor}
	PROV -> API: 201: OK
	API -> CoRIM : OK
	CoRIM -> User : Submit OK
end

@enduml