@startuml

participant "Veraison\nProvisioning" as PROV order 30
participant "Veraison\nProvisioning\nHandler" as Handler order 35
participant "Veraison\nProvisioning\nPluginMgr" as DecodePluginMgr order 40
participant "Veraison\nProvisioning\nPluginCtx" as Ctx order 45
participant "Veraison\nProvisioning\nStoreClient" as Sc order 50

group provisioning decode
	PROV -> Handler: Submit()
    	Handler -> DecodePluginMgr : Dispatch (MediaType, payload)
	DecodePluginMgr -> DecodePluginMgr : Get context of a specific\nDecoder Plugin(example PSA, DICE)\nbased on MediaType
	DecodePluginMgr -> Ctx : Decode(payload)
	Ctx -> DecodePluginMgr : DecoderRsp
    	DecodePluginMgr -> Handler : (response, err)
	Handler -> Sc : AddTrustAnchor(taReq)
	Sc -> Handler : taResult
	Handler -> Sc : AddSwComponents(swCompReq)
	Sc -> Handler : swCompResult
	Handler -> PROV: ok
end

@enduml