name: CI - Docs validation

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python (for some tools if needed)
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y shellcheck protobuf-compiler
          # Note: docker and docker-compose are pre-installed on GitHub Actions runners
          # Our validation scripts check for their presence but don't require them to run
      - name: Run validation
        run: |
          make validate
          make shellcheck
